dist: xenial

language: python

python:
  - "3.6"
  - "3.7"

cache:
  directories:
  - $HOME/.cmdstanpy

install:
  - pip install --quiet -r requirements.txt
  - pip install --quiet -r requirements-test.txt
  - pip install codecov
  # install cmdstanpy
  - pip install .
  # install cmdstan
  - python -m cmdstanpy.install_cmdstan
  - python ./scripts/clean_examples.py

after install:

script:
  # change dir and use installed version
  - mkdir new_dir
  - cd new_dir
  - flake8 --extend-ignore=E127,E201,E202,E203,E231,E252,E266,E402,E999,F841,W503,W605 --max-line-length=80 ../cmdstanpy ../test
  - pylint -v --rcfile=../.pylintrc ../cmdstanpy ../test
  - pytest -v ../test
  - python -m pip install -r ../requirements-optional.txt
  - python ../test/example_script.py
  - python ../scripts/clean_examples.py

after_success:
  - codecov # submit coverage
